# Generated by Django 4.2.2 on 2023-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
