# Generated by Django 4.2.2 on 2023-06-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(max_length=150, null=True, verbose_name='Полное имя'),
        ),
    ]
