# Generated by Django 4.2.2 on 2023-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0003_alter_profile_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fullName",
            field=models.CharField(max_length=150, verbose_name="Полное имя"),
        ),
    ]
