# Generated by Django 4.2.2 on 2023-06-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0004_alter_profile_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
