# Generated by Django 4.2.2 on 2023-07-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="users_app.avatar",
                verbose_name="Аватар",
            ),
        ),
    ]
