version: '3.9'

services:
  django-app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - megano.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media
      - ./megano/database:/django-app/database
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media
    depends_on:
      - django-app

volumes:
  static_volume:
  media_volume:

