version: '3.9'

services:
  django-app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - megano.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    volumes:
      - ./megano/database:/lsdjango-app/database