version: '3.9'

services:
  django-app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - megano.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '1m'
    env_file:
      - .env
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media
      - ./megano/database:/django-app/database
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media
    depends_on:
      - django-app

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      dockerfile: ./Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A celery --app=megano worker --loglevel=warning
    volumes:
      - ./megano/database:/django-app/database
    links:
      - redis
    depends_on:
      - redis

volumes:
  static_volume:
  media_volume:

