# Generated by Django 4.2.2 on 2023-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(null=True, verbose_name="Номер телефона"),
        ),
    ]
