# Generated by Django 4.2.2 on 2023-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["price"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False, verbose_name="Ограниченный тираж"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="shop_app.tag",
                verbose_name="Тэги",
            ),
        ),
    ]
