# Generated by Django 4.2.2 on 2023-09-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0014_alter_profile_email'),
        ('shop_app', '0007_basket_session_id_alter_basket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fullName', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('deliveryType', models.CharField(max_length=20, verbose_name='Тип доставки')),
                ('paymentType', models.CharField(max_length=20, verbose_name='Тип оплаты')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('products', models.ManyToManyField(related_name='orders', to='shop_app.product', verbose_name='Товары')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users_app.profile', verbose_name='Профиль')),
            ],
        ),
    ]
