# Generated by Django 4.2.2 on 2023-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.PositiveIntegerField(null=True, verbose_name="Номер телефона"),
        ),
    ]
