# Generated by Django 4.2.2 on 2023-09-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0014_alter_profile_email"),
        ("shop_app", "0010_alter_order_totalcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="users_app.profile",
                verbose_name="Профиль",
            ),
        ),
    ]
