# Generated by Django 4.2.2 on 2023-09-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0014_alter_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.CreateModel(
            name="ProductsInOrderCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_in_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество товаров в заказе"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_in_order_count",
                        to="shop_app.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_in_order_count",
                        to="shop_app.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Количество товаров в заказе",
                "verbose_name_plural": "Количества товаров в заказе",
            },
        ),
    ]
